version: "3.7"
services:
  app:
    image: kooldev/php:7.4-nginx
    ports:
     - "${KOOL_APP_PORT:-80}:80"
     - "${KOOL_WS_PORT:-6001}:6001"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
     - .:/app:delegated
     - $HOME/.ssh:/home/kool/.ssh:delegated
    networks:
     - kool_local
     - kool_global
  cache:
    image: redis:6-alpine
    volumes:
     - cache:/data:delegated
    networks:
     - kool_local

volumes:
  cache:

networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
