services:
  app:
    build: kool.deploy.dockerfile
    port: 80
    persists:
      - path: /app/storage
        sync: true
        chown: kool:kool
    public: true
    force: true
    recreate: false

  database:
    cloud: true

  cache:
    port: 6379
    recreate: true

after:
  migrate:
    service: app
    command: [ php, artisan, migrate, --force, --step]

environment: kool.deploy.env
